image: mono:latest

before_script:
 - apt-get update -y
 - apt-get install -y -qq fsharp libgomp1 libstdc++6 liblmdb0

build:
 stage: build
 script:        
 - mono .paket/paket.exe restore
 - chmod +x packages/metavcoin_z3_linux/output/z3-linux
 - chmod +x packages/SpecFlow/tools/specflow.exe
 - msbuild src/metavcoin.sln
 - cp packages/metavcoin_secp256k1_linux/output/libsecp256k1.so /usr/lib
 - ./run-tests
